### PR TITLE
Parameter list indentation

### PR DESCRIPTION
**Pull request by texdraft**
I didn't see your comment till now, sorry. Now `CWEAVE` obeys `-i` properly. Basically, function declarations and the beginning of function definitions are wrapped in `\1\1` and \2\2`; localizing the indents to be within the parameter list turned out to be much more difficult than I expected. Even though there have been no regressions in formatting, I would not be surprised to find out that the indentation position matters in certain situations.

Initially, I just changed the code to read

```
big_app(indent); app(indent); app_whatever();
```

instead of

```
app_whatever(); big_app(indent); app(indent);
```

but that ended up not working. It was possible for the `indent` scraps to be added before some productions output `\7` (`big_force`), causing the function names and types to be indented along with the parameters. To fix this I added a new kind of token (`dindent`), which gets emitted instead of `indent indent`. Upon output, the sequence of tokens `dindent big_force` is treated as `big_force indent indent`, achieving the desired effect.

The other change was to `prod.w`, to fix a formatting issue that I noticed only recently.

### CODE REVIEW

**Comment by ascherer** [comment]
Looks nice, with a minor point: `dindent` appears as `$\1\1{}$` in the TeX output; `\1\1` would be simpler.

**Comment by ascherer** [comment]
Got it.  Thanks for the fine work, again!
Plain `CWEAVE` now indents parameters in a similar layout for prototypical function headers as for classial headers.  The `-i` option will be extended in `CWEBbin` and TeX Live.

**Comment by ascherer** [comment]
There's a single small indentation issue, deeply buried in a change for `CTWILL` and easy to fix: https://github.com/ascherer/cwebbin/commit/dc9af9ec2c2ea69b4a561a0b9bdcee5e62558351

**Comment by texdraft** [comment]
The diagnosis is that

```
#if 0 static void...
```

eventually becomes

```
dindent inserted force
```
which is clearly problematic. Unfortunately this is proving difficult to fix. Skipping the `inserted` and letting the effective `dindent force` fall through to `@<Output a control...@>` doesn't seem to work; I don't think `force` leads to `@<Output saved |indent|...@>` getting executed. The logic in this part of the program is rather, shall we say, tangled.

Adding another state variable (or reusing `dindent_pending`) and doing some trickery to recognize the special case of `dindent inserted force` might be possible. But I fear that some restructuring of the logic will be necessary.

**Comment by ascherer** [comment]
No worries. I can live with the quick fix (and the extra space above `#if 0`).

**Comment by texdraft** [comment]
I realized just now (sorry) that a couple of the productions have been made outdated. Changes to `prod.w`:

```
@x
We use \\{in}, \\{out}, \\{back} and
\\{bsp} as shorthands for |indent|, |outdent|, |backup| and
|break_space|, respectively.
@y
We use \\{in}, \\{out}, \\{back},
\\{bsp} and \\{din} as shorthands for |indent|, |outdent|, |backup|,
|break_space| and |dindent| respectively.
@z
```

```
@x
\+& |exp| \altt|lbrace| |int_like| |decl|
    & |fn_decl| \altt|lbrace| |int_like| |decl|
        \hfill $F=E^*\,|in|\,|in|$ & \malt {\\{main}()$\{$}
           {\\{main}$(\\{ac},\\{av})$ \&{int} \\{ac};} \cr
@y
\+& |exp| \altt|lbrace| |int_like| |decl|
    & |fn_decl| \altt|lbrace| |int_like| |decl|
        \hfill $F=E^*\,|din|$ & \malt {\\{main}()$\{$}
           {\\{main}$(\\{ac},\\{av})$ \&{int} \\{ac};} \cr
@z
```

@x
\+& |decl_head| \altt|int_like| |lbrace| |decl| & |fn_decl|
                   \altt|int_like| |lbrace| |decl| \hfill $F=D\,|in|\,|in|$
                             & |long time () {|\cr
@y
\+& |decl_head| \altt|int_like| |lbrace| |decl| & |fn_decl|
                   \altt|int_like| |lbrace| |decl| \hfill $F=D\,|din|$
                             & |long time () {|\cr
@z
```

**Pull request closed without merging**
